/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividadeprojetinho;

import static atividadeprojetinho.AtividadeProjetinho.calcularIdade;
import static atividadeprojetinho.AtividadeProjetinho.maiorDeIdade;
import static atividadeprojetinho.AtividadeProjetinho.terceiraIdade;
import java.util.Scanner;
//import javax.swing.*;

/**
 *
 * @author mathi
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calculadora de Faixa Etária");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Digite o ano de nascimento aqui:");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        int anoAtual = 2025;
        Scanner teclado = new Scanner(System.in);
        
        System.out.println("Digite seu ano de nascimento aqui:");
        int anoNas = teclado.nextInt();
        
        int idade = calcularIdade(anoNas, anoAtual);
        
        boolean maior = maiorDeIdade(idade);
        boolean idoso = terceiraIdade(idade);
        
        if (maior == true){
            System.out.println("Maior de idade");
        }else if(idoso == true){
            System.out.println("Idoso");
        }else{
            System.out.println("Menor de idade");
        }
        
    } 
    
        //calcula a idade digitada
    public static int calcularIdade(int anoNas, int anoAtual){
            int idade = anoAtual - anoNas;
            return idade;
        }
    
    //verifica se o usuario é de maior
    public static boolean maiorDeIdade(int idade){
            if(idade >= 18 && idade<65){
                return true;
            }else{
                return false;
            }
        }
    
    //verifica se a pessoa ja é idosa e pode se aposentar
    public static boolean terceiraIdade(int idade){
        if(idade>=65){
            return true;
        }else{
            return false;
        }
    }
    
    
    private static void rodarTesteIntegracao(int anoNasc, int anoAtual, String esperado){
        int idade = AtividadeProjetinho.calcularIdade(anoNasc, anoAtual);
        String 
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
